/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package das;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.util.logging.Level;
import java.util.logging.Logger;

public class attendance extends javax.swing.JFrame {

    /**
     * Creates new form attendance
     */
    public attendance() {
        initComponents();
        
        jLabel4.setText(""+login1.id);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMatkul = new javax.swing.JComboBox<>();
        btnStatus = new javax.swing.JComboBox<>();
        btnSubmit = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));

        btnMatkul.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Object Oriented Programing", "Database", "Architecture and Computer Organization", "Software Engineering", "Digital System", "Basic Programing", " " }));
        btnMatkul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMatkulActionPerformed(evt);
            }
        });

        btnStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hadir", "Izin", "Tidak Hadir" }));
        btnStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStatusActionPerformed(evt);
            }
        });

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jLabel2.setText("Matakuliah");

        jLabel3.setText("Status Kehadiran");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("jLabel4");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.setBackground(new java.awt.Color(41, 68, 48));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Students Attendance");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 126, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(470, Short.MAX_VALUE)
                        .addComponent(btnSubmit)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancel)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnMatkul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(81, 81, 81))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMatkul, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubmit)
                    .addComponent(btnCancel))
                .addGap(104, 104, 104))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMatkulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMatkulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMatkulActionPerformed
    public static String s_id;
    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
       Connection conn = null;
       
       s_id =login1.id;
       try{
           conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/das?user=root&password=root");
           Statement stmnt = conn.createStatement();
           ResultSet rs = stmnt.executeQuery("Select * from student") ;
           
           String a, b = "";
            
            if(btnMatkul.getSelectedItem().equals("Object Oriented Programing")&& btnStatus.getSelectedItem().equals("Hadir")){
                a = btnMatkul.getSelectedItem().toString();
                b = btnStatus.getSelectedItem().toString();
                stmnt.executeUpdate("insert into attendance (`id`, `mata kuliah`, `Status Kehadiran`) values (\""+s_id+"\",\""+a+"\",\""+b+"\")");
                
            }
            else if(btnMatkul.getSelectedItem().equals("Object Oriented Programing")&& btnStatus.getSelectedItem().equals("Izin")){
                a = btnMatkul.getSelectedItem().toString();
                b = btnStatus.getSelectedItem().toString();                
                stmnt.executeUpdate("insert into attendance (`id`, `mata kuliah`, `Status Kehadiran`) values(\""+s_id+"\",\""+a+"\",\""+b+"\")");
                
            }
            else if(btnMatkul.getSelectedItem().equals("Object Oriented Programing")&& btnStatus.getSelectedItem().equals("Tidak Hadir")){
                a = btnMatkul.getSelectedItem().toString();
                b = btnStatus.getSelectedItem().toString();
                stmnt.executeUpdate("insert into attendance (`id`, `mata kuliah`, `Status Kehadiran`) values (\""+s_id+"\",\""+a+"\",\""+b+"\")");
                
            }
            else if(btnMatkul.getSelectedItem().equals("Database")&& btnStatus.getSelectedItem().equals("Hadir")){
                a = btnMatkul.getSelectedItem().toString();
                b = btnStatus.getSelectedItem().toString();
                stmnt.executeUpdate("insert into attendance (`id`, `mata kuliah`, `Status Kehadiran`) values (\""+s_id+"\",\""+a+"\",\""+b+"\")");
                
            }
            else if(btnMatkul.getSelectedItem().equals("Database")&& btnStatus.getSelectedItem().equals("Izin")){
                a = btnMatkul.getSelectedItem().toString();
                b = btnStatus.getSelectedItem().toString();
                stmnt.executeUpdate("insert into attendance (`id`, `mata kuliah`, `Status Kehadiran`) values (\""+s_id+"\",\""+a+"\",\""+b+"\")");
                
            }
            else if(btnMatkul.getSelectedItem().equals("Database")&& btnStatus.getSelectedItem().equals("Tidak Hadir")){
                a = btnMatkul.getSelectedItem().toString();
                b = btnStatus.getSelectedItem().toString();
                stmnt.executeUpdate("insert into attendance (`id`, `mata kuliah`, `Status Kehadiran`) values (\""+s_id+"\",\""+a+"\",\""+b+"\")");
                
            }
            else if(btnMatkul.getSelectedItem().equals("Architecture and Computer Organization")&& btnStatus.getSelectedItem().equals("Hadir")){
                a = btnMatkul.getSelectedItem().toString();
                b = btnStatus.getSelectedItem().toString();
                stmnt.executeUpdate("insert into attendance (`id`, `mata kuliah`, `Status Kehadiran`) values ("+s_id+"\",\""+a+"\",\""+b+"\")");
                
            }
            else if(btnMatkul.getSelectedItem().equals("Architecture and Computer Organization")&& btnStatus.getSelectedItem().equals("Izin")){
                a = btnMatkul.getSelectedItem().toString();
                b = btnStatus.getSelectedItem().toString();
                stmnt.executeUpdate("insert into attendance (`id`, `mata kuliah`, `Status Kehadiran`) values (\""+s_id+"\",\""+a+"\",\""+b+"\")");
                
            }
            else if(btnMatkul.getSelectedItem().equals("Architecture and Computer Organization")&& btnStatus.getSelectedItem().equals("Tidak Hadir")){
                a = btnMatkul.getSelectedItem().toString();
                b = btnStatus.getSelectedItem().toString();
                stmnt.executeUpdate("insert into attendance (`id`, `mata kuliah`, `Status Kehadiran`) values (\""+s_id+"\",\""+a+"\",\""+b+"\")");
                
            }
            else if(btnMatkul.getSelectedItem().equals("Digital System")&& btnStatus.getSelectedItem().equals("Hadir")){
                a = btnMatkul.getSelectedItem().toString();
                b = btnStatus.getSelectedItem().toString();
                stmnt.executeUpdate("insert into attendance (`id`, `mata kuliah`, `Status Kehadiran`) values (\""+s_id+"\",\""+a+"\",\""+b+"\")");
                
            }
            else if(btnMatkul.getSelectedItem().equals("Digital System")&& btnStatus.getSelectedItem().equals("Izin")){
                a = btnMatkul.getSelectedItem().toString();
                b = btnStatus.getSelectedItem().toString();
                stmnt.executeUpdate("insert into attendance (`id`, `mata kuliah`, `Status Kehadiran`) values (\""+s_id+"\",\""+a+"\",\""+b+"\")");
                
            }
            else if(btnMatkul.getSelectedItem().equals("Digital System")&& btnStatus.getSelectedItem().equals("Tidak Hadir")){
                a = btnMatkul.getSelectedItem().toString();
                b = btnStatus.getSelectedItem().toString();
                stmnt.executeUpdate("insert into attendance (`id`, `mata kuliah`, `Status Kehadiran`) values (\""+s_id+"\",\""+a+"\",\""+b+"\")");
               
            }
            else if(btnMatkul.getSelectedItem().equals("Software Engineering")&& btnStatus.getSelectedItem().equals("Hadir")){
                a = btnMatkul.getSelectedItem().toString();
                b = btnStatus.getSelectedItem().toString();
                stmnt.executeUpdate("insert into attendance (`id`, `mata kuliah`, `Status Kehadiran`) values (\""+s_id+"\",\""+a+"\",\""+b+"\")");
                
            }
            else if(btnMatkul.getSelectedItem().equals("Software Engineering")&& btnStatus.getSelectedItem().equals("Izin")){
                a = btnMatkul.getSelectedItem().toString();
                b = btnStatus.getSelectedItem().toString();
                stmnt.executeUpdate("insert into attendance (`id`, `mata kuliah`, `Status Kehadiran`) values (\""+s_id+"\",\""+a+"\",\""+b+"\")");
                
            }
            else if(btnMatkul.getSelectedItem().equals("Software Engineering")&& btnStatus.getSelectedItem().equals("Tidak Hadir")){
                a = btnMatkul.getSelectedItem().toString();
                b = btnStatus.getSelectedItem().toString();
                stmnt.executeUpdate("insert into attendance (`id`, `mata kuliah`, `Status Kehadiran`) values (\""+s_id+"\",\""+a+"\",\""+b+"\")");
                
            }
            else if(btnMatkul.getSelectedItem().equals("Basic Programing")&& btnStatus.getSelectedItem().equals("Hadir")){
                a = btnMatkul.getSelectedItem().toString();
                b = btnStatus.getSelectedItem().toString();
                stmnt.executeUpdate("insert into attendance (`id`, `mata kuliah`, `Status Kehadiran`) values (\""+s_id+"\",\""+a+"\",\""+b+"\")");
                
            }
            else if(btnMatkul.getSelectedItem().equals("Basic Programing")&& btnStatus.getSelectedItem().equals("Izin")){
                a = btnMatkul.getSelectedItem().toString();
                b = btnStatus.getSelectedItem().toString();
                stmnt.executeUpdate("insert into attendance (`id`, `mata kuliah`, `Status Kehadiran`) values (\""+s_id+"\",\""+a+"\",\""+b+"\")");
                
            }
            else if(btnMatkul.getSelectedItem().equals("Basic Programing")&& btnStatus.getSelectedItem().equals("Tidak Hadir")){
                a = btnMatkul.getSelectedItem().toString();
                b = btnStatus.getSelectedItem().toString();
                stmnt.executeUpdate("insert into attendance (`id`, `mata kuliah`, `Status Kehadiran`) values (\""+s_id+"\",\""+a+"\",\""+b+"\")");
                
            }
            super.dispose();
            new Student().setVisible(true);
            
            conn.close();
            
       }catch(SQLException ex){
           JOptionPane.showMessageDialog(null, "Connection Error");
           Logger.getLogger(attendance.class.getName()).log(Level.SEVERE,null,ex);
       }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        super.dispose();
        new login1().setVisible(true);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnStatusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new attendance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JComboBox<String> btnMatkul;
    private javax.swing.JComboBox<String> btnStatus;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}